FORMAT: 1A
HOST: http://api.amalet.local/api/

# amalyet api 

Amalyet offre cette api pour ces clients.

## offers [/offers]
### offers [GET] 
+ Response 200 (application/json)

        [
            {
                "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "name": "design code",
                "slug" : "project-52",
                "code" : "113151321",
                "description" : "full api for amalyet ......",
                "creator" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    }
                
                
            },
            {
                "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "name": "developpement WEB",
                "slug" : "project-52",
                "code" : "113151321"
                "description" : "full api for amalyet ......",
                "creator" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    }
                
                
            }
            
            
        ]
### offers/ [POST]
+ Request (application/json)

        {
                "name": "offfer 1",
                "description" : "this is an offer",
        }

+ Response 201 (application/json)


            
            {
                "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "name": "offfer 1",
                "description" : "this is an offer",
               
           }
           
            
        
            
+ Response 422 (application/json)

        {
            "name": "required",
            "description": "required"
        }

## offers/{offre} [/offers/offer]
### offers/offer [GET] 
+ Response 200 (application/json)

            {
                "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "name": "design code",
                "slug" : "project-52",
                "code" : "113151321",
                "description" : "full api for amalyet ......",
                "creator" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    }
                
                
            }
### offers/offer [DELETE] 
+ Response 200 (application/json)

            {
                "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "name": "design code",
                "slug" : "project-52",
                "code" : "113151321",
                "description" : "full api for amalyet ......",
                "creator" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    }
                
                
            }

## projects [/projects]
### projects [GET]
+ Response 200 (application/json)

        [
            {
                "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "name": "api amalyet",
                "slug" : "project-52",
                "code" : "113151321",
                "description" : "full api for amalyet ......",
                "creator" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    }, 
                "manager"  : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    },
                "type" : "value_project",    
                "staus" : "In Progress",
                "client" :  {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    },
                "admin" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    },
                "static_budget" : 2555, 
                "start_date" : "2019/01/02", 
                "end_date" : "2019/04/25",
                "offer_id" : 1,
                "is_favorite" : true, 
                "tags" : [],
                "tasks": [
                    {
                        "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa",
                        "name": "the first task",
                        "description" : "bla bla bla bla ....",
                        "planned_start_date": "2019/02/02", 
                        "planned_start_date": "2019/02/02",
                        "creator" : "", 
                        "assigne_to" : []
                    }
                ]
            }
            
        ]
### projects/ [POST]


+ Request (application/json)

        {
                "name": "api amalyet",
                "slug" : "project-52",
                "code" : "113151321",
                "description" : "full api for amalyet......",
                "manager_id"  :"511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "type" : "value_project",    
                "client_id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "admin_id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "static_budget" : 2555, 
                "start_date" : "2019/01/02", 
                "end_date" : "2019/04/25",
                "offer_id" : 1,
                "is_favorite" : true
        }

+ Response 201 (application/json)


            
            {
                "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "name": "api amalyet",
                "slug" : "project-52",
                "code" : "113151321"
                "description" : "full api for amalyet ......",
                "creator" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    }, 
                "manager"  : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    },
                "type" : "value_project",    
                "staus" : "In Progress",
                "client" :  {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    },
                "admin" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    },
                "static_budget" : 2555, 
                "start_date" : "2019/01/02", 
                "end_date" : "2019/04/25",
                "offer_id" : 1,
                "is_favorite" : true, 
                "tags" : [],
                
            }
            
        
            
+ Response 409 (application/json)

        {
            "filled": "required"
        }

## projects/{project} [/projects/{project}]       
### projects/{project} [GET]

+ Parameters
    + project (string) - UUId of the project 

+ Response 200 (application/json)



           {
                "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "name": "api amalyet",
                "slug" : "project-52",
                "code" : "113151321"
                "description" : "full api for amalyet ......",
                "creator" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    }, 
                "manager"  : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    },
                "type" : "value_project",    
                "staus" : "In Progress",
                "client" :  {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    },
                "admin" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    },
                "static_budget" : 2555, 
                "start_date" : "2019/01/02", 
                "end_date" : "2019/04/25",
                "offer_id" : 1,
                "is_favorite" : true, 
                "tags" : [],
                "tasks": [
                    {
                        "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa",
                        "name": "the first task",
                        "description" : "bla bla bla bla ....",
                        "planned_start_date": "2019/02/02", 
                        "planned_start_date": "2019/02/02",
                        "creator" : "",
                        "assigne_to" : []
                    }
                ]
            }
### projects/{project}[PUT]        

       
+ Parameters
    + project (string) - UUId of the project 

+ Request (application/json)

        {
                "project information": "offfer 1",
                
        }

+ Response 200 (application/json)



           {
                "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "name": "api amalyet",
                "slug" : "project-52",
                "code" : "113151321",
                "description" : "full api for amalyet ......",
                "creator" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    }, 
                "manager"  : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    },
                "type" : "value_project",    
                "staus" : "In Progress",
                "client" :  {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    },
                "admin" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    },
                "static_budget" : 2555, 
                "start_date" : "2019/01/02", 
                "end_date" : "2019/04/25",
                "offer_id" : 1,
                "is_favorite" : true, 
                "tags" : [],
                "tasks": [
                    {
                        "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa",
                        "name": "the first task",
                        "description" : "bla bla bla bla ....",
                        "planned_start_date": "2019/02/02", 
                        "planned_start_date": "2019/02/02",
                        "creator" : "",
                        "assigne_to" :[]
                        
                    }
                ]
            }
### projects/{project}/[DELETE]   
+ Parameters
    + project (string) - UUId of the project 

+ Response 200 (application/json)



           {
                "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "name": "api amalyet",
                "slug" : "project-52",
                "code" : "113151321",
                "description" : "full api for amalyet ......",
                "creator" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    }, 
                "manager"  : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    },
                "type" : "value_project",    
                "staus" : "In Progress",
                "client" :  {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    },
                "admin" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    },
                "static_budget" : 2555, 
                "start_date" : "2019/01/02", 
                "end_date" : "2019/04/25",
                "offer_id" : 1,
                "is_favorite" : true, 
                "tags" : [],
                "tasks": [
                    {
                        "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa",
                        "name": "the first task",
                        "description" : "bla bla bla bla ....",
                        "planned_start_date": "2019/02/02", 
                        "planned_end_date": "2019/02/02",
                        "creator" :  "",
                        "assigne_to" :[]
                        
                    }
                ]
            }

## projects/{project}/favorite [/projects/{project}/favorite]            
### projects/{project}/favorite [GET]   
+ Parameters
    + project (string) - UUId of the project 

+ Response 200 (application/json)

           {
              
            }
### projects/{project}/favorite [PUT]   
+ Parameters
    + project (string) - UUId of the project 

+ Response 200 (application/json)

           {
              
            }
            
## projects/{project}/share [/projects/{project}/share]
### projects/{project}/share [GET]   
+ Parameters
    + project (string) - UUId of the project 

+ Response 200 (application/json)

           {
              
            }
### projects/{project}/share [PUT]   
+ Parameters
    + project (string) - UUId of the project 

+ Response 200 (application/json)

           {
              
            }

## projects/{project}/tasks [/projects/{project}/tasks]
### projects/{project}/tasks [GET]
+ Response 200 (Application/json)

               [
                    {
                        "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa",
                        "name": "the first task",
                        "description" : "bla bla bla bla ....",
                        "planned_start_date": "2019/02/02", 
                        "planned_start_date": "2019/02/02",
                        "creator" : "", 
                        "assigne_to" : []
                    },
                     {
                        "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa",
                        "name": "the first task",
                        "description" : "bla bla bla bla ....",
                        "planned_start_date": "2019/02/02", 
                        "planned_start_date": "2019/02/02",
                        "creator" : "", 
                        "assigne_to" : []
                    }
                ]
### projects/{project}/tasks [POST] 
+ Response 200 (Application/json)

               {
                 
                }

## projects/{project}/tasks/{task} [/projects/{project}/taks/{task}]
### projects/{project}/tasks/{task} [GET] 
+ Response 200 (Application/json)

               {
                 
                }
### projects/{project}/tasks/{task} [PUT]
+ Response 200 (Application/json)

               {
                 
                }
### projects/{project}/tasks/{task} [DELETE]
+ Response 200 (Application/json)

               {
                 
                }