FORMAT: 1A
HOST: http://api.amalet.local/api/

# amalyet api 

Amalyet offre cette api pour ces clients.

## offers [/offers]
### offers [GET] 
+ Response 200 (application/json)

        [
            {
                "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "name": "design code",
                "slug" : "project-52",
                "code" : "113151321",
                "description" : "full api for amalyet ......",
                "creator" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    }
                
                
            },
            {
                "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "name": "developpement WEB",
                "slug" : "project-52",
                "code" : "113151321"
                "description" : "full api for amalyet ......",
                "creator" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    }
                
                
            }
            
            
        ]
### offers/ [POST]
+ Request (application/json)

        {
                "name": "offfer 1",
                "description" : "this is an offer",
        }

+ Response 201 (application/json)


            
            {
                "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "name": "offfer 1",
                "description" : "this is an offer",
               
           }
           
            
        
            
+ Response 422 (application/json)

        {
            "name": "required",
            "description": "required"
        }

## offers/{offre} [/offers/offer]
### offers/offer [GET] 
+ Response 200 (application/json)

            {
                "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "name": "design code",
                "slug" : "project-52",
                "code" : "113151321",
                "description" : "full api for amalyet ......",
                "creator" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    }
                
                
            }
### offers/offer [DELETE] 
+ Response 200 (application/json)

            {
                "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                "name": "design code",
                "slug" : "project-52",
                "code" : "113151321",
                "description" : "full api for amalyet ......",
                "creator" : {
                        "id" : "511fbd50-1f22-40ce-9abb-2d168f8729fa ",
                        "name" : "creator ",
                        "email" : "....@amalyet.com",
                        "avatar" : ""
                    }
                
                
            }

## projects [/projects]
### projects [GET]
+ Request
    
    + Headers
    
            Authorization: Bearer token 

+ Response 200 (application/json)

        {
        "data": [
                   {
                      "id": "1d5be0bb-4410-45c5-b248-1ca5d3610c66",
                      "name": "sssgd",
                      "description": "bla bla bla",
                      "code": "Amalyet-2514",
                      "static_buget": 8448,
                      "static_start_date": "2019-07-07 13:40:25",
                      "static_end_date": "2019-07-07 13:40:25",
                      "offer": {
                        "id": "9498b7f0-410b-47f2-8b25-d6c1a74764d7",
                        "name": "offer 1",
                        "description": null,
                        "type": "Offer",
                        "activities": [],
                        "budgets": [],
                        "created_at": "2019-07-07 13:37:56",
                        "updated_at": "2019-07-07 13:37:56"
                      },
                      "resouces": [
                        {
                          "user": {
                            "id": "220ce2c9-c2c9-48a8-84b9-0acfd7372a28",
                            "username": "superadmin",
                            "email": "superadmin@amalyet.com",
                            "roles": [
                              {
                                "id": "c712e673-0d90-462c-9394-fc56a94da689",
                                "name": "superadmin",
                                "created_at": "2019-07-07 13:03:57",
                                "permissions": []
                              }
                            ],
                            "created_at": "2019-07-07 13:03:57"
                          },
                          "assigned_role": "creator",
                          "is_favorite": false
                            }
                          ],
                          "status": "Open",
                          "created_at": "2019-07-07 13:40:25"
                        }
                    
        
            
                ]
            }
 
 
+ Response 401 (application/json)

        {
             "message": "Unauthenticated."
        }
        
            
### projects/ [POST]
+ Request 

    + Headers

            Authorization: Bearer token 

    + Body

            {
                "name" :"project title", 
                "description" : "Description is not required", 
                "code" :"Project-2514", 
                "status" :"ready" ,
                "static_buget" : 8448,
                "is_favorite" : false,
                "offer_id" : "845a0b2a-9678-41a8-ba1d-3be4e4e081cd",
                "manager_id" : "845a0b2a-9678-41a8-ba1d-3be4e4e081cd", 
                "admin_id" : "845a0b2a-9678-41a8-ba1d-3be4e4e081cd",
                "client_id" : "845a0b2a-9678-41a8-ba1d-3be4e4e081cdr"
                "static_start_date" : "2020-07-03 15:56:02"
                "static_end_date" : "2022-07-03 15:56:02"
            }
            


+ Response 201 (application/json)

            {
                  "data": {
                                "id": "f7040ea5-e66d-45bb-9562-ef2409138a4e",
                                "name": "sssgd",
                                "description": "bla bla bla",
                                "code": "Amalyet-2514",
                                "static_buget": 8448,
                                "static_start_date": {
                                  "date": "2019-07-08 09:45:47.733819",
                                  "timezone_type": 3,
                                  "timezone": "UTC"
                                },
                                "static_end_date": {
                                  "date": "2019-07-08 09:45:47.733830",
                                  "timezone_type": 3,
                                  "timezone": "UTC"
                                },
                                "offer": {
                                  "id": "9498b7f0-410b-47f2-8b25-d6c1a74764d7",
                                  "name": "offer 1",
                                  "description": null,
                                  "type": "Offer",
                                  "activities": [],
                                  "budgets": [],
                                  "created_at": "2019-07-07 13:37:56",
                                  "updated_at": "2019-07-07 13:37:56"
                                },
                                "resouces": [
                                  {
                                    "user": {
                                      "id": "220ce2c9-c2c9-48a8-84b9-0acfd7372a28",
                                      "username": "superadmin",
                                      "email": "superadmin@amalyet.com",
                                      "roles": [
                                        {
                                          "id": "c712e673-0d90-462c-9394-fc56a94da689",
                                          "name": "superadmin",
                                          "created_at": "2019-07-07 13:03:57",
                                          "permissions": []
                                        }
                                      ],
                                      "created_at": "2019-07-07 13:03:57"
                                    },
                                    "assigned_role": "creator",
                                    "is_favorite": false
                                  }
                                ],
                                "status": "Open",
                                "created_at": "2019-07-08 09:45:47"
                              }
                
            }
            
        
            
+ Response 422 (application/json)

        {
          "message": "The given data was invalid.",
          "errors": {
            "name": [
              "The name field is required."
            ],
            "description": [
              "The description field is required."
            ],
            "code": [
              "The code field is required."
            ],
            "client_id": [
              "The client id field is required."
            ],
            "is_favorite": [
              "The is favorite field is required."
            ]
          }
        }
+ Response 401 (application/json)

        {
             "message": "Unauthenticated."
        }


## projects/{project} [/projects/{project}]       
### projects/{project} [GET]
+ Request 

    + Headers

            Authorization: Bearer token 

+ Parameters
    + project (string) - UUId of the project 

+ Response 200 (application/json)

            {
                  "data": {
                    "id": "dc937cf2-fd42-4a76-a0b4-0dfcf381fd75",
                    "name": "sssgd",
                    "description": "bla bla bla",
                    "code": "Amalyet-2514",
                    "creator": {
                      "id": "90709005-de54-4863-9088-bbedf5262ef7",
                      "username": "superadmin",
                      "email": "superadmin@amalyet.com",
                      "roles": [
                        {
                          "id": "845a0b2a-9678-41a8-ba1d-3be4e4e081cd",
                          "name": "superadmin",
                          "created_at": "2019-07-03 11:40:48",
                          "permissions": []
                        }
                      ],
                      "created_at": "2019-07-03 11:40:48"
                    },
                    "manager": {
                      "id": "90709005-de54-4863-9088-bbedf5262ef7",
                      "username": "superadmin",
                      "email": "superadmin@amalyet.com",
                      "roles": [
                        {
                          "id": "845a0b2a-9678-41a8-ba1d-3be4e4e081cd",
                          "name": "superadmin",
                          "created_at": "2019-07-03 11:40:48",
                          "permissions": []
                        }
                      ],
                      "created_at": "2019-07-03 11:40:48"
                    },
                    "admin": {
                      "id": "90709005-de54-4863-9088-bbedf5262ef7",
                      "username": "superadmin",
                      "email": "superadmin@amalyet.com",
                      "roles": [
                        {
                          "id": "845a0b2a-9678-41a8-ba1d-3be4e4e081cd",
                          "name": "superadmin",
                          "created_at": "2019-07-03 11:40:48",
                          "permissions": []
                        }
                      ],
                      "created_at": "2019-07-03 11:40:48"
                    },
                    "static_buget": 8448,
                    "static_start_date": {
                      "date": "2019-07-04 08:42:19.380710",
                      "timezone_type": 3,
                      "timezone": "UTC"
                    },
                    "static_end_date": {
                      "date": "2019-07-04 08:42:19.380725",
                      "timezone_type": 3,
                      "timezone": "UTC"
                    },
                    "offer": {
                      "id": "677d1711-8ebd-47e6-97d7-c3ead28c8eeb",
                      "name": "offer 1",
                      "description": null,
                      "type": "Offer",
                      "activities": [],
                      "budgets": [],
                      "created_at": "2019-07-03 15:40:49",
                      "updated_at": "2019-07-03 15:40:49"
                    },
                    "is_favorite": true,
                    "created_at": "2019-07-04 08:42:19"
                  }
                }
                
            }
            
        
+ Response 401 (application/json)

        {
             "message": "Unauthenticated!"
        }
      
                    
+ Response 404 (application/json)

        {
             "message": "Resource not found!"
        }
        
### projects/{project}[PUT]        
+ Request 

    + Headers

            Authorization: Bearer token 
    
    + Body

            {
                "name" :"project title", 
                "description" : "Description is not required", 
                "code" :"Project-2514", 
                "status" : 1 ,
                "static_buget" : 8448,
                "is_favorite" : false,
                "offer_id" : "845a0b2a-9678-41a8-ba1d-3be4e4e081cd",
                "manager_id" : "845a0b2a-9678-41a8-ba1d-3be4e4e081cd", 
                "admin_id" : "845a0b2a-9678-41a8-ba1d-3be4e4e081cd",
                "client_id" : "845a0b2a-9678-41a8-ba1d-3be4e4e081cdr"
                "static_start_date" : "2020-07-03 15:56:02"
                "static_end_date" : "2022-07-03 15:56:02"
            }

+ Parameters
    + project (string) - UUId of the project  
    
    

+ Response 422 (application/json)


            {
              "message": "The given data was invalid.",
              "errors": {
                "name": [
                  "The name field is required."
                ],
                "description": [
                  "The description field is required."
                ],
                "code": [
                  "The code field is required."
                ],
                "client_id": [
                  "The client id field is required."
                ],
                "is_favorite": [
                  "The is favorite field is required."
                ]
              }
            }
           
+ Response 401 (application/json)

        {
             "message": "Unauthenticated!"
        }
        
### projects/{project}/[DELETE]   
+ Parameters
    + project (string) - UUId of the project 

+ Response 200 (application/json)



           {
              "data": {
                "id": "f7040ea5-e66d-45bb-9562-ef2409138a4e",
                "name": "sssgd",
                "description": "bla bla bla",
                "code": "Amalyet-2514",
                "static_buget": 8448,
                "static_start_date": "2020-02-02",
                "static_end_date": "2019-07-08 09:45:47",
                "offer": null,
                "resouces": [
                  {
                    "user": {
                      "id": "220ce2c9-c2c9-48a8-84b9-0acfd7372a28",
                      "username": "superadmin",
                      "email": "superadmin@amalyet.com",
                      "roles": [
                        {
                          "id": "c712e673-0d90-462c-9394-fc56a94da689",
                          "name": "superadmin",
                          "created_at": "2019-07-07 13:03:57",
                          "permissions": []
                        }
                      ],
                      "created_at": "2019-07-07 13:03:57"
                    },
                    "assigned_role": "creator",
                    "is_favorite": false
                  }
                ],
                "status": "In Progress",
                "created_at": "2019-07-08 09:45:47"
              }
            }

+ Response 401 (application/json)

        {
             "message": "Unauthenticated!"
        }
        
+ Response 404 (application/json)

        {
             "message": "Unauthenticated!"
        }

##profile  [/profile/projects]
### profile/projects [GET]
+ Request 

    + Headers

            Authorization: Bearer token 

+ Response  200 (Application/json)

            {
              "data": [
                {
                  "id": "1d5be0bb-4410-45c5-b248-1ca5d3610c66",
                  "name": "sssgd",
                  "description": "bla bla bla",
                  "code": "Amalyet-2514",
                  "static_buget": 8448,
                  "static_start_date": "2019-07-07 13:40:25",
                  "static_end_date": "2019-07-07 13:40:25",
                  "offer": {
                    "id": "9498b7f0-410b-47f2-8b25-d6c1a74764d7",
                    "name": "offer 1",
                    "description": null,
                    "type": "Offer",
                    "activities": [],
                    "budgets": [],
                    "created_at": "2019-07-07 13:37:56",
                    "updated_at": "2019-07-07 13:37:56"
                  },
                  "is_favorite": false,
                  "status": "Open",
                  "created_at": "2019-07-07 13:40:25"
                }
                    ]
            }

##profile/projects/{project}/share [/profile/projects/{project}/share]
###profile/projects/{project}/share [put]
+ Request 

    + Headers

            Authorization: Bearer token 
    
  + Body

            {
                 "users" :[ 
                    {
                          "id" : "6ae8d013-1a3e-4324-bfc3-1a0f85b67138",
                          "role" : "resource"
                    }
                 ]
            }
            
+ Params 
    +project UUID of the project


+ Response 200 (Application/json)

             {
                  "messsage": "success"
             }
                
            
 
 
## projects/{project}/tasks [/projects/{project}/tasks]
### projects/{project}/tasks [GET]
+ Response 200 (Application/json)

               [
                    {
                        "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa",
                        "name": "the first task",
                        "description" : "bla bla bla bla ....",
                        "planned_start_date": "2019/02/02", 
                        "planned_start_date": "2019/02/02",
                        "creator" : "", 
                        "assigne_to" : []
                    },
                     {
                        "id": "511fbd50-1f22-40ce-9abb-2d168f8729fa",
                        "name": "the first task",
                        "description" : "bla bla bla bla ....",
                        "planned_start_date": "2019/02/02", 
                        "planned_start_date": "2019/02/02",
                        "creator" : "", 
                        "assigne_to" : []
                    }
                ]
                
+ Response 422 (Application/json)
 
 
                {
                  "message": "The given data was invalid.",
                  "errors": {
                    "users": [
                      "The users field is required."
                    ]
                  }
                }
### projects/{project}/tasks [POST] 
+ Response 200 (Application/json)

               {
                 
                }

## projects/{project}/tasks/{task} [/projects/{project}/taks/{task}]
### projects/{project}/tasks/{task} [GET] 
+ Response 200 (Application/json)

               {
                 
                }
### projects/{project}/tasks/{task} [PUT]
+ Response 200 (Application/json)

               {
                 
                }
### projects/{project}/tasks/{task} [DELETE]
+ Response 200 (Application/json)

               {
                 
                }